In [ ]:
#1)import the numpy package under the name np

In [1]:
import numpy as np

In [2]:
#2)create null vector of size 10


In [5]:
null_vec=np.zeros(10)
null_vec


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#3)create a null vector of size 10 but the fifth values which is 1

In [4]:
null_vec[4]=1
null_vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
#4)create a vector with values ranging from 10 to 49

In [7]:
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
#5)reverse a vector 



In [10]:
x=np.arange(10,50)
x
rev_aray=x[::-1]
rev_aray

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [11]:
#6)create a 3x3 matrix with values ranging from 0 to 8

In [13]:
matrix=np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
#7)find the indicies of non zero elements from[1,2,0,0,4,0]

In [17]:
indicies=np.nonzero([1,2,0,0,4,0])
indicies

(array([0, 1, 4], dtype=int64),)

In [18]:
#8)creare 3x3x3 array with random values

In [20]:
matrix_random=np.random.random((3,3,3))
matrix_random

array([[[0.90729328, 0.73910656, 0.38207439],
        [0.6869761 , 0.09597985, 0.10712332],
        [0.1679203 , 0.80120969, 0.42369391]],

       [[0.6136144 , 0.38697872, 0.87317903],
        [0.88028799, 0.3133587 , 0.5683482 ],
        [0.37985797, 0.5892586 , 0.06291884]],

       [[0.35367899, 0.48248053, 0.64431776],
        [0.60807176, 0.29810434, 0.92504234],
        [0.73558049, 0.19626532, 0.5587085 ]]])

In [21]:
#9)create a random vector of size 30 and find the mean value

In [22]:
ran_vec=np.random.random(30)
ran_vec
mean_of_ran_vec=np.mean(ran_vec)
mean_of_ran_vec

0.536881027819251

In [1]:
#10)create a 2d array with 1 on the border and 0 inside

In [4]:

import numpy as np
x=np.ones((5,5))
print("original array")
print(x)

x[1:-1,1:-1]=0
x

original array
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
#11)create 8x8 matrix and fill it with a checkbporad pattern

In [8]:
x=np.ones((3,3))
x
print("check board pattern")
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
x

check board pattern


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [9]:
#12)what is the difference between sets,lists,tuples and dictionaries


In [ ]:
#LIST:- they are dynamic sized arrays,need not be homogeneous.
#SETS:-it is unordered collection of data,iterable,mutable and has no duplicate elements
#TUPLES:-collection python objects seperated by commas.it is similar to list in terms of indexing and repetition but tuple is immutable unlike lists are mutable
#DICTIONARIES:-it is unordered collection of data values ,used to store values like a mapping. it holds key:value pair. 

In [10]:
#13)print first 10 natural numbers using while loop


In [19]:
i=0
while(i<=10):
    print(i)
    i+=1

0
1
2
3
4
5
6
7
8
9
10


In [21]:
#14)print the numbers from -10 to -1 using for loop

In [23]:

 for i in range(-10,0):
    print(i)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


In [24]:
#15)print the message "done " after successfull execution of any for a loop


In [27]:
for i in range(0,11):
    print(i)
else:
        print("done")


0
1
2
3
4
5
6
7
8
9
10
done


In [ ]:
#16)create a random vector of size 10 and sort it

In [36]:
rand=np.random.random((10))
rand
sorted_rand=np.sort(rand)
sorted_rand

array([0.00246546, 0.25430161, 0.30451732, 0.36520763, 0.36530013,
       0.59528371, 0.60877409, 0.63378526, 0.64818885, 0.65967022])

In [31]:
#17)Execute any three math functions using numpy


In [32]:
#ceil() function is used to return the ceiling value of array values which is smallest integer value greater than the array element
import numpy as np
arr=np.array([12.202,91.37,22.11,37.33])
print(np.ceil(arr))

[13. 92. 23. 38.]


In [34]:
#mean() can be calculated by adding all the items of arrays dividing by number of array elements


import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("mean of array")
print(np.mean(arr))

mean of array
5.0


In [35]:
#nonzero() is used to find the location of th non-zero elements from the array

import numpy as np
arr=np.array([0,12,3,0,0,7,37,73])
print(arr.nonzero())

(array([1, 2, 5, 6, 7], dtype=int64),)
